[project]
name = "geofs-website-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "jsonschema>=4.25.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
